export default [
    {
        name: "Crime Detection System",
        field: "visual detection",
        abstract: "A visual detection system to identify possible criminal activities and report a human operator",
        description: "The goal of this project is to prepare a dataset made of images of lethal weapons and other criminal imagery such as explosions or bleeding. Once the dataset is prepared the AI will be trained to recognize such imagery and then tested for accuracy.",
        projectLeader: "Imam Alimsultanov",
        projectLeaderMail: "imam.alimsultanov@gmail.com",
        projectLeaderPhone: 2345678901,
        projectMembers: ["Imam Alimsultanov", "Imam Alimsultanov2", "Imam Alimsultanov3", "Imam Alimsultanov4"],
        goals: ["Make a dataset", "Train the AI", "Test the AI on images and videos", "Test the AI IRL"],
        goalCompletion: [0, 0, 0, 0],
        githubLink: "github.com/asxvzxzc",
        img: "https://www.techcube.co.uk/wp-content/uploads/2017/09/cctv-camera.jpg",
    },
    {
        name: "Story Maker",
        field: "text generation",
        abstract: "A text generator which creates stories based on user input.",
        description: "The goal of this project is to create an AI that can create a story after given a set of inputs. It will then be asked about various topics and adjusted accordingly",
        projectLeader: "Adamska Gurluckovic",
        projectLeaderMail: "adamska.gurluckovic@gmail.com",
        projectLeaderPhone: 2345678901,
        projectMembers: ["Adamska Gurluckovic", "Adamska Gurluckovic2", "Adamska Gurluckovic3", "Adamska Gurluckovic4", "Adamska Gurluckovic5"],
        goals: ["Make a dataset", "Train the AI", "Test the AI through prompts"],
        goalCompletion: [1, 1, 1],
        githubLink: "github.com/asdfghh",
        img: "",
    },
    {
        name: "Cancer Detector",
        field: "pattern recognition/visual detection",
        abstract: "A patern recognition system that scans a given user for possible signs of cancer and then detect certain patterns that may suggest cancer and alert the user.",
        description: "The goal of this project is to prepare a dataset made of patterns of medical stuff (idfk) related to cancer. Once the dataset is prepared the AI will be trained to recognize such imagery and then tested for accuracy.",
        projectLeader: "Dr. Phil",
        projectLeaderMail: "phil.adwadas@gmail.com",
        projectLeaderPhone: 123456789,
        projectMembers: ["Dr. Phil", "Dr. Phil1", "Dr. Phil2", "Dr. Phil3"],
        goals: ["Make a dataset", "Train the AI", "Test the AI on images and videos", "Test the AI IRL"],
        goalCompletion: [0, 1, 1, 0],
        githubLink: "github.com/adadwawdadw",
        img: "",
    },
]